/*
 * DSDT for Windows XP on Hyper-V Generation 2 VMs booted through CSMWrap
 * (csmwrap.ini: acpi_dsdt = \dsdt.aml, together with madt_pcat_compat = true).
 *
 * XP SP3's acpi.sys cannot load the Gen2 firmware DSDT: Device (\_SB.VMOD)
 * runs CreateQWordField (an ACPI 2.0 opcode, 0x8F) at table load time, and
 * XP's AML interpreter has no handler for it, so ACPIInitializeDDB fails
 * with bugcheck 0xA5 (0x11, 8, ...).
 *
 * This table follows the structure of the Hyper-V Generation 1 DSDT (the
 * generation Microsoft supports XP on, revision 1, OEM "MSFTVM" "MSFTVM02")
 * for every device that also exists on Gen2, and keeps Gen2's hardware
 * facts: no PCI devices, no ISA bridge, no 8259/8254/8042/DMA/FDC, VMBus on
 * IRQ 5, PM registers at I/O 0x400. Only ACPI 1.0b constructs are used: the
 * table is revision 1 (32-bit integers), there is no module-level code and
 * nothing that needs the per-VM "BIOS" SystemMemory region of the firmware
 * DSDT (its address follows the VM's memory size).
 *
 * Left out compared with the Gen2 firmware DSDT: the ACPI0004 module device
 * (its low MMIO range is a fixed PCI0 window here, its high range above
 * 4 GB is dropped), NVDIMM, TPM, SGX EPC, the processor aggregator,
 * battery/AC, the VM generation counter (needs the BIOS region) and S4.
 */
DefinitionBlock ("", "DSDT", 1, "MSFTVM", "CSMWXP01", 0x00000001)
{
    Scope (\_SB)
    {
        /*
         * Processor objects in \_SB as on Gen1, ACPI processor IDs 1..N
         * matching Hyper-V's MADT (Processor ID = APIC ID + 1). Windows
         * only starts processors listed in the MADT, so declaring more
         * than the VM has is harmless. No P_BLK: C1 only, as on Gen1.
         * Generated by build.sh.
         */
        Include ("cpus.asl")

        /*
         * Gen2 has no PCI, but XP needs a PCI root bus anyway: acpi.sys's
         * IRQ arbiter (AcpiArbCrackPRT) calls the PCI interrupt routing
         * interface that pci.sys provides when a PNP0A03 bus starts, for
         * every device with an IRQ, and dereferences NULL without one
         * (bugcheck 0x7E while allocating the RTC's IRQ 8). The bus is
         * empty (config reads return all ones). The devices below sit
         * directly on it, where Gen1 has them under its PIIX4 ISA bridge
         * \_SB.PCI0.SBRG.
         *
         * Its _CRS is Gen1's \_SB.PCI0 _CRS without the A0000-BFFFF window
         * (RAM on Gen2) and the 64-bit windows: the I/O windows, plus one
         * memory window in the low MMIO gap for the VMBus devices that
         * need guest physical address space, e.g. synthetic video's VRAM.
         * Gen1 also declares that space only here; VMBS has just IRQs.
         * Linux looks for it the same way: vmbus_acpi_add() collects the
         * DWord/QWord address descriptors of VMBS's _CRS and then of the
         * nearest ancestor that has any (Gen1 PCI0, Gen2 \_SB.VMOD), and
         * hyperv_drm fails with "Failed to allocate mmio" without one.
         *
         * The Gen2 low MMIO gap is [4 GB - LowMemoryMappedIoSpace, 4 GB)
         * whatever the VM's memory size (the firmware's VMOD reads it from
         * its BIOS region: 0xF8000000 + 128 MB by default, measured on
         * 512 MB-4 GB VMs). Hyper-V only accepts 128 MB-3.5 GB for that
         * setting, so 0xF8000000-0xFFFFFFFF is always in the gap; the
         * window stops below the I/O APIC, TPM and local APIC (SYSR). The
         * boot frame buffer (8 MB) sits at the start of the gap, inside
         * the window at the default setting, where Linux's hyperv_drm
         * keeps its VRAM; with a larger gap it moves the VRAM into the
         * window. XP's acpi.sys reports the window as a shared resource
         * of the PCI bus, and hvfb and bootvid map the frame buffer
         * without claiming it, so nothing in XP competes for this range.
         */
        Device (PCI0)
        {
            Name (_HID, EisaId ("PNP0A03"))   // PCI bus
            Name (_BBN, Zero)
            Name (_UID, Zero)
            Name (_CRS, ResourceTemplate ()
            {
                WordBusNumber (ResourceProducer, MinFixed, MaxFixed, PosDecode,
                    0x0000, 0x0000, 0x00FF, 0x0000, 0x0100)
                IO (Decode16, 0x0CF8, 0x0CF8, 0x01, 0x08)
                WordIO (ResourceProducer, MinFixed, MaxFixed, PosDecode, EntireRange,
                    0x0000, 0x0000, 0x0CF7, 0x0000, 0x0CF8)
                WordIO (ResourceProducer, MinFixed, MaxFixed, PosDecode, EntireRange,
                    0x0000, 0x0D00, 0xFFFF, 0x0000, 0xF300)
                DWordMemory (ResourceProducer, PosDecode, MinFixed, MaxFixed, Cacheable, ReadWrite,
                    0x00000000, 0xF8000000, 0xFEBFFFFF, 0x00000000, 0x06C00000)
            })

            Device (RTC0)
            {
                Name (_HID, EisaId ("PNP0B00"))   // AT real-time clock
                Name (_CRS, ResourceTemplate ()
                {
                    IO (Decode16, 0x0070, 0x0070, 0x00, 0x02)
                    IRQNoFlags () {8}
                })
            }

            /*
             * COM1/COM2 as on Gen1, but fixed: Gen1 reads and programs them
             * through its Super I/O, Gen2 has them only when COM ports are
             * configured (the firmware DSDT checks the BIOS region's SCFG
             * byte). A static table cannot read that region, so _STA probes
             * the 16550 scratch register instead: absent ports read 0xFF.
             */
            Device (UAR1)
            {
                Name (_UID, One)
                Name (_DDN, "COM1")
                Name (_HID, EisaId ("PNP0501"))   // 16550A-compatible COM port
                OperationRegion (UREG, SystemIO, 0x03F8, 0x08)
                Field (UREG, ByteAcc, NoLock, Preserve)
                {
                    Offset (0x07),
                    USCR,   8
                }
                Method (_STA, 0, Serialized)
                {
                    Local0 = USCR
                    USCR = 0x5A
                    Local1 = USCR
                    USCR = Local0
                    If ((Local1 == 0x5A))
                    {
                        Return (0x0F)
                    }

                    Return (Zero)
                }
                Name (_CRS, ResourceTemplate ()
                {
                    IRQ (Edge, ActiveHigh, Exclusive, ) {4}
                    IO (Decode16, 0x03F8, 0x03F8, 0x01, 0x08)
                })
            }

            Device (UAR2)
            {
                Name (_UID, 0x02)
                Name (_DDN, "COM2")
                Name (_HID, EisaId ("PNP0501"))   // 16550A-compatible COM port
                OperationRegion (UREG, SystemIO, 0x02F8, 0x08)
                Field (UREG, ByteAcc, NoLock, Preserve)
                {
                    Offset (0x07),
                    USCR,   8
                }
                Method (_STA, 0, Serialized)
                {
                    Local0 = USCR
                    USCR = 0x5A
                    Local1 = USCR
                    USCR = Local0
                    If ((Local1 == 0x5A))
                    {
                        Return (0x0F)
                    }

                    Return (Zero)
                }
                Name (_CRS, ResourceTemplate ()
                {
                    IRQ (Edge, ActiveHigh, Exclusive, ) {3}
                    IO (Decode16, 0x02F8, 0x02F8, 0x01, 0x08)
                })
            }

            /*
             * VMBus as Gen1's \_SB.PCI0.SBRG.VMBS, the node the XP
             * Integration Services 6.3 were built against: _HID "VMBus" is
             * the ACPI\VMBus hardware ID vmbus.inf binds to (Gen2 has _HID
             * MSFT1000 and "VMBus" only as _CID), and like Gen1 it asks for
             * IRQs 5 and 7. vmbus.sys connects to them with
             * IoConnectInterrupt to get interrupt vectors; on Gen2 VMBus
             * interrupts arrive through the SynIC, IRQ 5 is what the Gen2
             * firmware assigns and IOAPIC pin 7 is unused. _HID "VMBus" is
             * not a well-formed PNP/ACPI ID, hence iasl -vw 6033.
             */
            Device (VMBS)
            {
                Name (STA, 0x0F)
                Name (_HID, "VMBus")
                Name (_DDN, "VMBUS")
                Method (_DIS, 0, NotSerialized)
                {
                    STA &= 0x0D
                }

                Method (_PS0, 0, NotSerialized)
                {
                    STA |= 0x0F
                }

                Method (_STA, 0, NotSerialized)
                {
                    Return (STA)
                }

                Method (_PS3, 0, NotSerialized)
                {
                }

                Name (_CRS, ResourceTemplate ()
                {
                    IRQ (Edge, ActiveHigh, Exclusive, ) {5}
                    IRQ (Edge, ActiveHigh, Exclusive, ) {7}
                })
            }
        }

        /*
         * Resources nothing else may take, like Gen1's \_SB.PCI0.SBRG.OSYS:
         * the PM register block (PM1a event/control, PM timer and GPE0 at
         * 0x400-0x40F, reset register 0x433), the Hyper-V BIOS device ports
         * the firmware AML uses (0x28-0x2F) and the I/O APIC and local APIC
         * (the Gen2 firmware DSDT lists the APICs in \_SB.VMOD.APIC).
         */
        Device (SYSR)
        {
            Name (_HID, EisaId ("PNP0C02"))   // motherboard resources
            Name (_UID, One)
            Name (_CRS, ResourceTemplate ()
            {
                IO (Decode16, 0x0028, 0x0028, 0x01, 0x08)
                IO (Decode16, 0x0400, 0x0400, 0x01, 0x40)
                Memory32Fixed (ReadWrite, 0xFEC00000, 0x00001000)
                Memory32Fixed (ReadWrite, 0xFEE00000, 0x00001000)
            })
        }
    }

    /*
     * Sleep states: the SLP_TYP values of the Gen2 firmware DSDT (0 for S0
     * and S5; SLP_EN with SLP_TYP 0 written to PM1a_CNT 0x404 turns the VM
     * off), in Gen1's four-element package form.
     */
    Name (\_S0, Package (0x04)
    {
        Zero,
        Zero,
        Zero,
        Zero
    })
    Name (\_S5, Package (0x04)
    {
        Zero,
        Zero,
        Zero,
        Zero
    })
}
