/*
 * bootvid.dll for Windows XP on machines without VGA hardware.  See
 * bootvid.c for the design.
 */
#ifndef BOOTVID_H
#define BOOTVID_H

/* The screen the kernel draws on: VGA mode 12h, 640x480 with 16 colours. */
#define BV_SCREEN_WIDTH         640
#define BV_SCREEN_HEIGHT        480
#define BV_COLORS               16

/* Built-in font: 8x13 cells; VidDisplayString advances 14 rows per line. */
#define BV_CHAR_WIDTH           8
#define BV_CHAR_HEIGHT          13
#define BV_LINE_HEIGHT          14

/* font.c (generated by tools/mkfont.py): code page 437, row 0 at the top. */
extern const UCHAR BvFont[256][BV_CHAR_HEIGHT];

/*
 * The exports, as XP SP3's own bootvid.dll and the kernel's imports define
 * them.  All are __stdcall and exported by undecorated name (bootvid.def).
 * Coordinates are pixels on the 640x480 screen; colours are indices into
 * the 16-entry palette.  Rectangles given as Left/Top/Right/Bottom are
 * inclusive.
 */
BOOLEAN NTAPI VidInitialize(BOOLEAN SetMode);
VOID NTAPI VidResetDisplay(BOOLEAN HalReset);
VOID NTAPI VidCleanUp(VOID);
ULONG NTAPI VidSetTextColor(ULONG Color);
VOID NTAPI VidSetScrollRegion(ULONG Left, ULONG Top, ULONG Right, ULONG Bottom);
VOID NTAPI VidDisplayString(PUCHAR String);
VOID NTAPI VidDisplayStringXY(PUCHAR String, ULONG Left, ULONG Top, BOOLEAN Transparent);
VOID NTAPI VidSolidColorFill(ULONG Left, ULONG Top, ULONG Right, ULONG Bottom, UCHAR Color);
VOID NTAPI VidBitBlt(PUCHAR Buffer, ULONG Left, ULONG Top);
VOID NTAPI VidBufferToScreenBlt(PUCHAR Buffer, ULONG Left, ULONG Top, ULONG Width,
                                ULONG Height, ULONG Delta);
VOID NTAPI VidScreenToBufferBlt(PUCHAR Buffer, ULONG Left, ULONG Top, ULONG Width,
                                ULONG Height, ULONG Delta);

#endif /* BOOTVID_H */
