[package]
name = "formats"
description = "File formats used by hvkit: PE images, byte patterns"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
flate2 = { version = "1", default-features = false, features = ["zlib-rs"] }
lzxd = "0.2"
