#!/usr/bin/env python3
"""Generate bootvid's 8x13 code page 437 font from a BDF font.

  mkfont.py 8x13.bdf > drivers/bootvid/font.c

The intended source is 8x13.bdf of the X.Org "misc-misc" fonts (Misc Fixed
8x13, ISO 10646 encoded, by Markus Kuhn et al.), which is in the public
domain ("Public domain font.  Share and enjoy.").  It is not part of this
repository; get it from X.Org's font/misc-misc module or a mirror, e.g.
https://github.com/openbsd/xenocara/blob/master/font/misc-misc/8x13.bdf

XP's text is in the OEM code page, so the 256 cells follow code page 437:
0x00 and 0x7F-style control cells use the IBM PC graphic characters, 0x80-0xFF
the CP437 letters, box drawing and symbols.  Cells whose glyph is missing
from the BDF stay blank.
"""
import sys

WIDTH, HEIGHT = 8, 13

# IBM PC graphic characters shown for the control codes 0x01-0x1F and 0x7F.
CP437_LOW = ("\0☺☻♥♦♣♠•◘○◙♂♀♪♫☼"
             "►◄↕‼¶§▬↨↑↓→←∟↔▲▼")


def cp437(code):
    if code < 0x20:
        return ord(CP437_LOW[code]) if code else None
    if code == 0x7F:
        return 0x2302
    if code == 0xFF:
        return None                 # no-break space: blank
    return ord(bytes([code]).decode("cp437"))


def parse_bdf(path):
    glyphs = {}
    ascent = None
    with open(path, encoding="latin-1") as f:
        lines = iter(f.read().splitlines())
    for line in lines:
        if line.startswith("FONT_ASCENT "):
            ascent = int(line.split()[1])
        if not line.startswith("STARTCHAR"):
            continue
        enc, bbx, rows = None, None, []
        for line in lines:
            if line.startswith("ENCODING "):
                enc = int(line.split()[1])
            elif line.startswith("BBX "):
                bbx = tuple(int(v) for v in line.split()[1:5])
            elif line == "BITMAP":
                for line in lines:
                    if line == "ENDCHAR":
                        break
                    rows.append(int(line, 16) << (8 * (4 - (len(line) + 1) // 2)))
                break
        if enc is not None and enc >= 0 and bbx:
            glyphs[enc] = (bbx, rows)
    if ascent is None:
        sys.exit("no FONT_ASCENT")
    return glyphs, ascent


def render(glyph, ascent):
    """Place a BDF glyph in an 8x13 cell; returns 13 row bytes (bit 7 = left)."""
    (w, h, xoff, yoff), rows = glyph
    cell = [0] * HEIGHT
    top = ascent - (yoff + h)
    for i, bits in enumerate(rows):
        y = top + i
        if not 0 <= y < HEIGHT:
            continue
        # rows were left-aligned to 32 bits; shift into the cell by xoff
        row = (bits >> (24 + xoff)) & 0xFF if xoff >= 0 else (bits >> 24 << -xoff) & 0xFF
        cell[y] |= row
    return cell


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    glyphs, ascent = parse_bdf(sys.argv[1])
    out = sys.stdout
    out.write("/*\n * 8x13 font for bootvid.dll, code page 437 (generated by tools/mkfont.py).\n"
              " *\n * Glyphs from the X.Org misc-misc font 8x13.bdf (Misc Fixed, ISO 10646-1),\n"
              " * which is in the public domain.  Row 0 is the top; bit 7 is the leftmost\n"
              " * pixel.\n */\n")
    out.write('#include <ntdef.h>\n#include "bootvid.h"\n\n')
    out.write("const UCHAR BvFont[256][BV_CHAR_HEIGHT] = {\n")
    missing = []
    for code in range(256):
        uc = cp437(code)
        if uc is None or uc not in glyphs:
            cell = [0] * HEIGHT
            if uc is not None:
                missing.append("%02X (U+%04X)" % (code, uc))
        else:
            cell = render(glyphs[uc], ascent)
        label = " '%c'" % code if 0x20 < code < 0x7F and code != 0x5C else ""
        out.write("    /* %02X%s */ {%s},\n" % (code, label, ", ".join("0x%02X" % b for b in cell)))
    out.write("};\n")
    if missing:
        print("mkfont: no glyph for " + ", ".join(missing), file=sys.stderr)


if __name__ == "__main__":
    main()
